vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    profile_picture:
      uri_prefix: /images/profiles
      upload_destination: "%kernel.project_dir%/public/images/profiles"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
